# Generated by Django 5.2 on 2025-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_remove_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Максимум 250 символів', max_length=250, verbose_name='Категорія'),
        ),
    ]
